package scratch
import scratch.circe.{IntId, LongId, ShortId}
package object ids {
 case class AuditId(innerId: Long) extends LongId(innerId)
 case class ContractDetailsId(innerId: Int) extends IntId(innerId)
 case class CreditNoteId(innerId: Int) extends IntId(innerId)
 case class CrmContractorId(innerId: Int) extends IntId(innerId)
 case class DescriptionId(innerId: Int) extends IntId(innerId)
 case class InvoiceId(innerId: Int) extends IntId(innerId)
 case class InvoiceLineId(innerId: Int) extends IntId(innerId)
 case class IpDataId(innerId: Int) extends IntId(innerId)
 case class PersonalDetailsId(innerId: Int) extends IntId(innerId)
 case class PipelineDataId(innerId: Int) extends IntId(innerId)
 case class RgbColorId(innerId: Short) extends ShortId(innerId)
 case class CsrId(innerId: Int) extends IntId(innerId)
 case class LocalCompanyId(innerId: Int) extends IntId(innerId)
 case class StreetAddressId(innerId: Int) extends IntId(innerId)
 case class AgencyId(innerId: Int) extends IntId(innerId)
 case class AgentId(innerId: Int) extends IntId(innerId)
 case class AllocationId(innerId: Int) extends IntId(innerId)
 case class PermitTypeId(innerId: Short) extends ShortId(innerId)
 case class PermitApplicationEventTypeId(innerId: Short) extends ShortId(innerId)
 case class PermitId(innerId: Int) extends IntId(innerId)
 case class PermitApplicationEventId(innerId: Int) extends IntId(innerId)
 case class PermitPeriodId(innerId: Short) extends ShortId(innerId)
 case class PermitExtensionExpiryId(innerId: Int) extends IntId(innerId)
 case class PermitResponseEventTypeId(innerId: Short) extends ShortId(innerId)
 case class PermitResponseEventId(innerId: Int) extends IntId(innerId)
 case class CountryNumeric(innerId: Short) extends ShortId(innerId)
 case class CurrencyNumericCode(innerId: Short) extends ShortId(innerId)
}
